### ISSUE TITLE
MarginX cross chain swap test plan design

### ISSUE THREAD

**Issue by ethan-pundix** [FunctionX-SG/QA#14]
Test Plan: Margin X Cross-Chain Swap Project

### **1. Objective**
The objective is to test the functionality of this cross-chain swap platform to ensure it operates securely and efficiently under various conditions. Key goals include:

- Verify the accuracy and security of cross-chain transactions.
- Checking fee calculations and token precision.
- Test the correctness of inter-chain communication and UI behavior in different wallet connection states..
- Assess the platform’s usability (UI/UX).
- Evaluate smart contract security and performance.
- Ensuring compliance with user experience and security requirements

### **2. Scope of Testing**

- Functional Testing
- Security Testing
- Performance Testing
- Compatibility Testing
- User Experience Testing
- Compliance Testing

### **3. Test Environment**

- Blockchain Networks: Ethereum, BSC (Binance Smart Chain), Polygon, Arbitrum and Zeta.
- Tools: Metamask, Wallets App (e.g., f(x)wallet), cross-chain bridge tools.
- Contract Deployment Platforms: Remix IDE or Truffle.
- Test Networks: Zeta Testnet, BSC Testnet.
- Frameworks: Mocha, Chai, Hardhat, Web3.js, Ethers.js.

### **4. Testing Scope**
**4.1 Functional Testing**
**Objective:** Ensure all features work as expected.

- Token Swap Functionality
> - Test if users can successfully swap tokens between different blockchains.
> - Validate the correctness of fee calculations.
> - Test the delay and accuracy of cross-chain bridges.
> - Handle edge cases where swaps fail due to network issues.
> - Test cross-chain bridge and swap functionality, such as BSC.USDT <-> Zeta.Zeta, added in the staging environment after completing regular bridge test cases.

- Wallet Connection
> - Test both connected and not connected wallet states to ensure the UI behaves correctly when the wallet is not connected.

- Token Precision (Decimals)
> - Ensure token precision (decimals) behaves correctly in the UI, which may slightly differ from current rules.
> - Test tokens with different decimal values, such as 18 and 6 decimals.

- Fee Model
> - Test if transaction fees are calculated according to the rules.
> - Validate consistency of fee calculations across different blockchains.

**4.2 Security Testing**
**Objective:** Ensure the security of the platform and smart contracts.

- Smart Contract Audits

> - Check for potential reentrancy vulnerabilities.
> - Test for overflow and underflow issues.
> - Validate secure inter-chain messaging.
> - Ensure wallet signatures and transactions are secure.

- Vulnerability Testing

> - Simulate attacks for common vulnerabilities like reentrancy, flash loan attacks, governance attacks, etc.
> - Test private key management and asset protection mechanisms.

**4.3 Performance Testing**
**Objective:** Check system performance under high loads and during peak transaction periods.

- Throughput Testing

> - Test platform speed under high transaction volumes per second.
> - Validate transaction consistency across multiple blockchains.
> - Monitor cross-chain swap performance under network delays.

- Resource Usage

> - Test CPU and memory usage to ensure optimized contract execution.

**4.4 Compatibility Testing**
**Objective:** Ensure the platform runs correctly across various devices and network conditions.

- Cross-Platform Testing
> - Validate platform compatibility across different blockchains (e.g., Ethereum, BSC, Polygon).
> - Test user experience across devices (desktop, mobile).
> - Validate browser compatibility (Chrome, Firefox, etc.).

**4.5 User Experience Testing**
**Objective:** Ensure the platform is simple and intuitive to use.

- UI Testing
> - Test the usability and responsiveness of the user interface.
> - Ensure users receive appropriate feedback and confirmations during token swaps.
> - Verify that the UI behaves as expected when the wallet is not connected.

- User Journey
> - Test the complete cross-chain transaction process, including asset locking, transfer, and unlocking.
> - Ensure users receive proper feedback in case of transaction failures or delays.

**4.6 Compliance Testing**
**Objective:** Ensure the platform complies with local and international cryptocurrency regulations.

- KYC/AML Testing
> - Validate the compliance of identity verification and risk management mechanisms.
> - Check whether cross-chain transactions comply with Anti-Money Laundering (AML) policies.

**5. Testing Timeline**

- Functional Testing: 2 Days
- Integration Testing: 1 Days
- Full Regression Testing: 1 Days

**6. Test Exit Criteria**

- All test cases pass successfully with no critical bugs or performance issues.

**7. Test Reporting**

- After testing is completed, generate a detailed report documenting all results, error logs, and suggested fixes.

**Comment by ethan-pundix** [comment]
Hi @CheeKeat10 @JianAn30 
The test plan for the cross-chain swap project is ready. It covers key areas like functionality, security, performance, compatibility, user experience, and compliance. Could you kindly review it and let me know if there are any changes or suggestions? Thanks! I expect to start testing on Thursday. Please let me know when can test on main-net, thanks!

**Comment by CheeKeat10** [comment]
Hi @ethan-pundix , can we add below test case scenarios?

- add wallet connected & not connected to make sure ui is working as expected when wallet not collected
- the token precision(decimals) test case could be slightly different from current ui rules, test different decimals token(18 & 6)
- the bridge and swap(for example: BSC.USDT <-> Zeta.Zeta) funcitonality is added into staging site, can add this after finish normal brige test case.

![image](https://github.com/user-attachments/assets/f1be982f-875b-48c1-baca-eec296dc03dc)

Thanks

**Comment by ethan-pundix** [comment]
Hi @CheeKeat10 
Thank you for your feedback. I will consolidate these scenarios and incorporate them into my test cases. Thanks!
