### ISSUE TITLE
Menus Disappear and No Burger Menu in Mobile View on Trade Web

### ISSUE THREAD

**Issue by ChristianGunawanX** [FunctionX-SG/QA#50]
Steps to Reproduce:
1. Open the Trade Web (https://trade.marginx.io/) on a mobile view browser.
2. Observe that the menus are not displayed, and no burger menu is provided.

Actual Result:
The menus are completely hidden, and no burger menu or alternative navigation is visible.

Expected Result:
The platform should display a responsive burger menu or alternative navigation option in mobile view to allow users to access all menus and features.

Attachment
https://github.com/user-attachments/assets/1cf431cd-9109-4e83-bfb4-02a9faa8eee4

**Comment by JianAn30** [comment]
Updated

**Comment by ChristianGunawanX** [comment]
Passed
https://trade.marginx.io/home
19 Dec 2024

https://github.com/user-attachments/assets/97ca25a7-f132-4ec9-b4de-d879cafab4c4
